# Generated by Django 5.2.8 on 2025-11-21 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zakovat_bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='file_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='file_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
