# Generated by Django 5.2.8 on 2025-11-22 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zakovat_bot', '0002_questions_file_id_questions_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='questioned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
