# Generated by Django 5.2.8 on 2026-07-21 11:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zakovat_bot', '0003_users_phone_number_alter_questions_questioned_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('is_active', models.BooleanField(default=True)),
                ('admin_id', models.BigIntegerField()),
                ('action', models.CharField(max_length=100)),
                ('details', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Broadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('is_active', models.BooleanField(default=True)),
                ('source_chat_id', models.BigIntegerField()),
                ('message_ids', models.JSONField(default=list)),
                ('admin_id', models.BigIntegerField()),
                ('status', models.CharField(choices=[('scheduled', 'Rejalashtirilgan'), ('in_progress', 'Jarayonda'), ('done', 'Yakunlangan'), ('cancelled', 'Bekor qilingan')], default='in_progress', max_length=20)),
                ('target_filter', models.CharField(default='all', max_length=150)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('success_count', models.IntegerField(default=0)),
                ('failed_count', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('is_active', models.BooleanField(default=True)),
                ('chat_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('ott_name', models.CharField(max_length=255)),
                ('ott_type', models.CharField(choices=[('davlat', 'Davlat'), ('xorijiy', 'Xorijiy'), ('nodavlat', 'Nodavlat')], default='davlat', max_length=20)),
                ('tag', models.CharField(blank=True, max_length=100, null=True)),
                ('bot_is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='telegramadminsid',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='telegramadminsid',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Bosh admin'), ('operator', 'Admin (operator)'), ('observer', 'Kuzatuvchi')], default='operator', max_length=20),
        ),
        migrations.CreateModel(
            name='BroadcastResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('is_active', models.BooleanField(default=True)),
                ('delivered', models.BooleanField(default=False)),
                ('error_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('message_id', models.BigIntegerField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('broadcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='zakovat_bot.broadcast')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broadcast_results', to='zakovat_bot.channel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
