# Generated by Django 5.2.8 on 2026-07-21 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zakovat_bot', '0004_auditlog_broadcast_channel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcastresult',
            name='deleted_from_channel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='broadcastresult',
            name='message_ids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
