# Generated by Django 5.2.8 on 2026-08-10 12:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zakovat_bot', '0007_seed_chat_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('is_active', models.BooleanField(default=True)),
                ('telegram_id', models.BigIntegerField()),
                ('username', models.CharField(blank=True, max_length=64, null=True)),
                ('full_name', models.CharField(max_length=60)),
                ('phone', models.CharField(max_length=20)),
                ('type', models.CharField(choices=[('Taklif', 'Taklif'), ('Murojaat', 'Murojaat'), ('Shikoyat', 'Shikoyat'), ('Tashabbus', 'Tashabbus'), ('Savol', 'Savol')], default='Murojaat', max_length=20)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('new', '🆕 Yangi'), ('in_review', "🔄 Ko'rib chiqilmoqda"), ('answered', '✅ Javob berildi')], default='new', max_length=16)),
                ('response', models.TextField(blank=True, null=True)),
                ('answered_by', models.BigIntegerField(blank=True, null=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
