# Generated by Django 5.2.8 on 2026-08-12 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zakovat_bot', '0008_appeal'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatevent',
            name='arrival_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatevent',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatevent',
            name='reminder_hours',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='chatevent',
            name='send_start_message',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='chatevent',
            name='slug',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='chatevent',
            name='subscription_channel',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
